server:
    port: 8081
message:
    greeting: Welcome Home Mi Dear
    welcome: Welcome To GitHub Updated Again
spring:
	datasource:
		url:jdbc:mysql://localhost:3306/pae_web
spring:
	datasource:
		username:root
spring:
	datasource:
		password:
# Keep the connection alive if idle for a long time (needed in production)
spring:
	datasource:
		testWhileIdle:true
spring:
	datasource:
		validationQuery:SELECT 1

message:
    greeting: Welcome Home Mi Dear
    welcome: Welcome To GitHub Updated prod