server:
    port: 8081
message:
    greeting: Welcome Home Mi Dear
    welcome: Welcome To GitHub Updated Again
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/test
	username:root
	password:
message:
    greeting: Welcome Home Mi Dear
    welcome: Welcome To GitHub Updated Again
